"""
Django settings for devops project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import  os
import  environ


env = environ.Env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 读取.env文件，在服务器项目的根路径上要创建一个
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# 日志文件
LOGIN_URL = os.path.join(BASE_DIR,'logs')
if not os.path.exists(LOGIN_URL):
    os.makedirs(LOGIN_URL)

# ansibleyml目录
ANSIBLE_BOOK = os.path.join(BASE_DIR, 'ansible_playbooks')

#判断这个目录是否存在
if not os.path.exists(ANSIBLE_BOOK):
    os.makedirs(ANSIBLE_BOOK)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yg+(j7g#_(27_d^8nl&t#rt%b8ow4k%ptc&m^4)!^e&o61-eba'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'apps.dev_auth.apps.DevAuthConfig',
    'apps.dev_ansible.apps.DevAnsibleConfig',
    'apps.dev_linux.apps.DevLinuxConfig',
    'apps.dev_home.apps.DevHomeConfig'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 开发环境
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'devops',        # 数据库名称
#         'USER': 'root',             # 数据库用户名
#         'PASSWORD': '123456',  # 数据库密码
#         'HOST': '127.0.0.1',           # 数据库主机
#         'PORT': '3306',
#         'OPTIONS': {
#             'charset': 'utf8mb4',  # 使用 UTF-8 字符集
#             # 其他 MySQL 特定选项
#         },
#         # 数据库端口
#     }
# }
# 生产
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        "NAME": env.str('DB_NAME', 'devops'),
        "USER": env.str('DB_USER', "root"),
        "PASSWORD": env.str("DB_PASSWORD", "123456"),
        "HOST": env.str('DB_HOST', 'localhost'),
        "PORT": env.str('DB_PORT', 3306),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# 文件图片
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

#允许所有域名跨域访问
CORS_ORIGIN_ALLOW_ALL = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
   'DEFAULT_AUTHENTICATION_CLASSES': ['apps.dev_auth.authentications.JWTAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.dev_auth.permissions.GlobalAutoPermission',
        # 'rest_framework.permissions.IsAuthenticated',
    ],
}

# redis
#CELERY相关配置
# CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
# # 指定结果的接受地址
# # CELERY_RESULT_BACKEND = 'redis://username:passwd@host:port/db'
# CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'
# CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


#缓存设置
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/3",
#     }
# }

CELERY_BROKER_URL = env.str('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/1')
CELERY_RESULT_BACKEND = env.str('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/2')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env.str('CACHE_URL', "redis://127.0.0.1:6379/3"),
    }
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            # 直接放在项目根目录，避免权限问题
            "filename": os.path.join(LOGIN_URL, "devops.log"),
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # 使用空字符串捕获所有 logger.info
        "": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
        },
    },
}