# Generated by Django 5.2.8 on 2025-12-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansibleconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_playbook_path', models.CharField(max_length=200, verbose_name='剧本路径')),
                ('host_file', models.CharField(max_length=200, verbose_name='host文件')),
                ('target_group', models.CharField(max_length=200, verbose_name='目标组')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Ansible 部署配置',
            },
        ),
        migrations.CreateModel(
            name='Ansiblecomd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '成功'), (1, '失败'), (2, '执行中'), (3, '未执行')], default=3, verbose_name='状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('source_output', models.TextField(blank=True, default='', verbose_name='成功日志')),
                ('error_output', models.TextField(blank=True, default='', verbose_name='错误日志')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_ansible.ansibleconfig', verbose_name='关联配置')),
            ],
            options={
                'verbose_name': 'Ansible 命令记录',
                'verbose_name_plural': 'Ansible 命令记录',
            },
        ),
    ]
