# Generated by Django 5.2.8 on 2025-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='父菜单ID')),
                ('order_num', models.IntegerField(null=True, verbose_name='显示顺序')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(max_length=1, null=True, verbose_name='菜单类型（M目录 C菜单 F按钮）')),
                ('perms', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='角色权限字符串')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('menus', models.ManyToManyField(db_table='sys_role_menu', related_name='roles', to='dev_auth.sysmenu', verbose_name='拥有权限')),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户头像')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户邮箱')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('login_date', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '激活')], default=0, verbose_name='帐号状态（0正常 1停用）')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('roles', models.ManyToManyField(db_table='sys_user_role', related_name='users', to='dev_auth.sysrole', verbose_name='拥有角色')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
