# Generated by Django 5.2.8 on 2025-12-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
